program hahahahaha;
begin
  writeln(' Podaj ilosc kulawych kuropatw w garazu sasiada');
  readln;
  writeln(' Jaka predkosc rozwija jaskolka afrykanska w druga strone ?');
  readln;
  writeln(' Ile liczy jamnik ?');
  readln;
  writeln(' Ilu widzow mial film "Lezacy z pudlami" ?');
  readln;
  writeln('          ****************************');
  writeln('          *                          *');
  writeln('          *      HA KURDE HA !!!     *');
  writeln('          *                          *');
  writeln('          ****************************');
  readln;
end.